# Generated by Django 4.2.23 on 2025-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=256)),
                ('has_reminder', models.BooleanField(default=False)),
                ('reminder', models.DateTimeField()),
                ('status', models.CharField(choices=[('W', 'Wating'), ('P', 'In Progress'), ('C', 'Complete')], max_length=2)),
                ('color', models.CharField(default='#000000', max_length=8)),
                ('proirity', models.IntegerField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')])),
            ],
        ),
    ]
