# Generated by Django 4.2.23 on 2025-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_task_id_task_identication_key_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proirity',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], max_length=2),
        ),
    ]
